/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigcalculator;

//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL OS
 */
public class DataForm extends javax.swing.JFrame {

    private MainCalc previousMain;
   
    public DataForm() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\DELL OS\\Desktop\\BigCalculator\\src\\bigcalculator\\img\\iconframe1.png");    
        setIconImage(icon);    
        setTitle("BigInteger Calculator");
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
       try {
        String dbURL = "jdbc:mysql://localhost/big_calculator";
        String username = "root";
        String password = "";
        Class.forName("com.mysql.jdbc.Driver");
        conn = (Connection) DriverManager.getConnection(dbURL, username, password);
        if (conn != null) {
         System.out.println("Kết nối thành công");
        }
        // Câu lệnh xem dữ liệu
        String sql = "select * from DATACALCULATE";
        // Tạo đối tượng thực thi câu lệnh Select
        st = (Statement) conn.createStatement();
        // Thực thi
        rs = st.executeQuery(sql);
        Vector data = null;
        tblModel.setRowCount(0);
        // Nếu không có thông tin không tồn tại
        if (rs.isBeforeFirst() == false) {
         JOptionPane.showMessageDialog(this, "Chưa có thông tin!");
         return;
        }
        // Trong khi chưa hết dữ liệu
        while (rs.next()) {
         data = new Vector();
         data.add(rs.getInt("ID"));
         data.add(rs.getString("m"));
         data.add(rs.getString("n"));
         data.add(rs.getString("type"));
         data.add(rs.getString("result"));
         data.add(rs.getString("remainder"));
         data.add(rs.getTimestamp("date_calc"));
         // Thêm một dòng vào table model
         tblModel.addRow(data);
        }
        jTable1.setModel(tblModel); // Thêm dữ liệu vào table
       } catch (Exception e) {
         e.printStackTrace();
       }
    }
    
    public DataForm(MainCalc c) {
        this.previousMain = c;
        initComponents();
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
       try {
        String dbURL = "jdbc:mysql://localhost/big_calculator";
        String username = "root";
        String password = "";
        Class.forName("com.mysql.jdbc.Driver");
        conn = (Connection) DriverManager.getConnection(dbURL, username, password);
        if (conn != null) {
         System.out.println("Kết nối thành công");
        }
        // Câu lệnh xem dữ liệu
        String sql = "select * from DATACALCULATE";
        // Tạo đối tượng thực thi câu lệnh Select
        st = (Statement) conn.createStatement();
        // Thực thi
        rs = st.executeQuery(sql);
        Vector data = null;
        tblModel.setRowCount(0);
        // Nếu không có thông tin không tồn tại
        if (rs.isBeforeFirst() == false) {
         JOptionPane.showMessageDialog(this, "Chưa có thông tin!");
         return;
        }
        // Trong khi chưa hết dữ liệu
        while (rs.next()) {
         data = new Vector();
         data.add(rs.getInt("ID"));
         data.add(rs.getString("m"));
         data.add(rs.getString("n"));
         data.add(rs.getString("type"));
         data.add(rs.getString("result"));
         data.add(rs.getString("remainder"));
         data.add(rs.getTimestamp("date_calc"));
         // Thêm một dòng vào table model
         tblModel.addRow(data);
        }
        jTable1.setModel(tblModel); // Thêm dữ liệu vào table
       } catch (Exception e) {
         e.printStackTrace();
       }
    }
    
    private String header[] = {"ID", "A", "B", "Phép tính", "Kết quả","Dư","Thời điểm tính toán"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigcalculator/img/icons8-back-to-48.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("CƠ SỞ DỮ LIỆU TÍNH TOÁN");

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigcalculator/img/icons8-checkmark-48.png"))); // NOI18N
        jButton2.setText("Chọn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigcalculator/img/delete-database.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(338, 338, 338))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.previousMain.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        System.out.println(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int indexRow = jTable1.getSelectedRow();
        if (indexRow != -1){
            String number1 = (String)tblModel.getValueAt(indexRow, 1);
            String number2 = (String)tblModel.getValueAt(indexRow, 2);
            String operator = (String)tblModel.getValueAt(indexRow, 3);
            this.previousMain = new MainCalc(number1, number2, operator);
            this.previousMain.setVisible(true);
        this.setVisible(false);
        this.dispose();
        } else {
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f,"Vui lòng chọn dòng dữ liệu bạn cần nhập từ CSDL");  
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        int indexRow = jTable1.getSelectedRow();
        int index = (int)tblModel.getValueAt(indexRow, 0);
        if (indexRow != -1){
            try {
              // create the mysql database connection
                String dbURL = "jdbc:mysql://localhost/big_calculator";
                String username = "root";
                String password = "";
                Class.forName("com.mysql.jdbc.Driver");
                conn = (Connection) DriverManager.getConnection(dbURL, username, password);
                if (conn != null) {
                 System.out.println("Kết nối thành công");
                }

                // create the mysql delete statement.
                // i'm deleting the row where the id is "3", which corresponds to my
                // "Barney Rubble" record.
                String query = "delete from datacalculate where ID=" + index;
                
                PreparedStatement preparedStmt = conn.prepareStatement(query);

                
                // execute the preparedstatement
                preparedStmt.executeUpdate();
                JFrame f=new JFrame();
                JOptionPane.showMessageDialog(f,"Bạn đã xóa phép tính có ID=" + index);  
                System.out.println(query);
                tblModel.removeRow(indexRow);
                conn.commit();
                conn.close();
            }
            catch (Exception e){
              System.out.println(e);
            }
        } else {
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f,"Vui lòng chọn dòng dữ liệu bạn cần nhập từ CSDL");  
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    public void connectDatabase() throws ClassNotFoundException{
        Connection conn = null;
        String dbURL = "jdbc:mysql://localhost/big_calculator";
        String username = "root";
        String password = "";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection) DriverManager.getConnection(dbURL, username, password);
            if (conn != null) {
                System.out.println("Kết nối thành công");
            }    
        } catch (SQLException e) {
                e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataForm().setVisible(true);
            }
        });
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
